version: '3.8'

services:
  # 건설 관리 시스템 웹 애플리케이션
  construction-app:
    build: .
    container_name: construction-management-system
    ports:
      - "3000:80"  # 호스트의 3000 포트를 컨테이너의 80 포트와 연결
    volumes:
      - app-data:/usr/share/nginx/html/data  # 데이터 지속성을 위한 볼륨
    restart: unless-stopped  # 컨테이너 자동 재시작
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.construction-app.rule=Host(`localhost`)"
      - "traefik.http.services.construction-app.loadbalancer.server.port=80"

volumes:
  app-data:
    driver: local

networks:
  default:
    name: construction-network